export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_GETBYID_REQUEST = "ORDER_GETBYID_REQUEST";
export const ORDER_GETBYID_SUCCESS = "ORDER_GETBYID_SUCCESS";
export const ORDER_GETBYID_FAIL = "ORDER_GETBYID_FAIL";

export const ORDER_GETALL_REQUEST = "ORDER_GETALL_REQUEST";
export const ORDER_GETALL_SUCCESS = "ORDER_GETALL_SUCCESS";
export const ORDER_GETALL_FAIL = "ORDER_GETALL_FAIL";
