export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";
export const PRODUCT_DETAIL_RESET = "PRODUCT_DETAIL_RESET";


export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_ADMIN_DELETE_REQUEST = "PRODUCT_ADMIN_DELETE_REQUEST";
export const PRODUCT_ADMIN_DELETE_SUCCESS = "PRODUCT_ADMIN_DELETE_SUCCESS";
export const PRODUCT_ADMIN_DELETE_FAIL = "PRODUCT_ADMIN_DELETE_FAIL";
export const PRODUCT_ADMIN_DELETE_RESET = "PRODUCT_ADMIN_DELETE_RESET";

export const PRODUCT_ADMIN_UPDATE_REQUEST = 'PRODUCT_ADMIN_UPDATE_REQUEST'
export const PRODUCT_ADMIN_UPDATE_SUCCESS = 'PRODUCT_ADMIN_UPDATE_SUCCESS'
export const PRODUCT_ADMIN_UPDATE_FAIL = 'PRODUCT_ADMIN_UPDATE_FAIL'
export const PRODUCT_ADMIN_UPDATE_RESET = 'PRODUCT_ADMIN_UPDATE_RESET'

export const PRODUCT_ADMIN_CREATE_REQUEST = 'PRODUCT_ADMIN_CREATE_REQUEST'
export const PRODUCT_ADMIN_CREATE_SUCCESS = 'PRODUCT_ADMIN_CREATE_SUCCESS'
export const PRODUCT_ADMIN_CREATE_FAIL = 'PRODUCT_ADMIN_CREATE_FAIL'
export const PRODUCT_ADMIN_CREATE_RESET = 'PRODUCT_ADMIN_CREATE_RESET'

export const PRODUCT_REVIEW_REQUEST = 'PRODUCT_REVIEW_REQUEST'
export const PRODUCT_REVIEW_SUCCESS = 'PRODUCT_REVIEW_SUCCESS'
export const PRODUCT_REVIEW_FAIL = 'PRODUCT_REVIEW_FAIL'
export const PRODUCT_REVIEW_RESET = 'PRODUCT_REVIEW_RESET'